import os
import json
import sys

# Add parent directory to path to import ai_manager
sys.path.append(os.path.join(os.path.dirname(__file__), '..', 'ai_service'))
try:
    from ai_manager import AIService
except ImportError:
    # Mock for standalone testing
    class AIService:
        def __init__(self, config): pass
        def generate_completion(self, prompt, provider=None, model=None): return "['00', 'FF', '00']"

class SpriteStudio:
    def __init__(self, config_path='../ai_service/config.json'):
        self.ai = AIService(config_path)
        self.prompt_path = os.path.join(os.path.dirname(__file__), '..', 'ai_service', 'prompts', 'sprite_artist.txt')
        
    def _load_system_prompt(self):
        if os.path.exists(self.prompt_path):
            with open(self.prompt_path, 'r') as f:
                return f.read()
        return "Generate C64 Sprite Data."

    def generate_sprite(self, description: str) -> list:
        """
        Asks the AI to generate a sprite based on the description.
        Returns a list of 63 integers (bytes).
        """
        system_prompt = self._load_system_prompt()
        full_prompt = f"{system_prompt}\n\nUSER REQUEST: {description}"
        
        response = self.ai.generate_completion(full_prompt)
        
        # Parse the response (expecting a JSON-like list of hex strings)
        try:
            # Clean up response to ensure it's just the list
            clean_resp = response.strip()
            if clean_resp.startswith("```"):
                clean_resp = clean_resp.split("\n", 1)[1].rsplit("\n", 1)[0]
            
            # Simple parsing heuristic
            clean_resp = clean_resp.replace("'", '"')
            hex_list = json.loads(clean_resp)
            
            byte_data = [int(h, 16) for h in hex_list]
            
            # Pad or truncate to 63 bytes (standard C64 sprite)
            if len(byte_data) < 63:
                byte_data += [0] * (63 - len(byte_data))
            return byte_data[:63]
            
        except Exception as e:
            print(f"Error parsing AI response: {e}")
            print(f"Raw Response: {response}")
            return [0] * 63

    def save_sprite(self, data: list, filename: str, format='bin'):
        """
        Saves sprite data to disk.
        """
        if format == 'bin':
            with open(filename, 'wb') as f:
                f.write(bytearray(data + [0])) # +1 padding byte for 64-byte alignment
        elif format == 'asm':
            with open(filename, 'w') as f:
                f.write("; Sprite Data generated by SuperCPU Sprite Studio\n")
                f.write("Sprite:\n")
                for i in range(0, 63, 3):
                    chunk = data[i:i+3]
                    hex_str = ",".join([f"${b:02X}" for b in chunk])
                    f.write(f"    .byte {hex_str}\n")
                f.write("    .byte $00 ; Padding\n")

# Example Usage
if __name__ == "__main__":
    studio = SpriteStudio()
    data = studio.generate_sprite("A space invader alien")
    studio.save_sprite(data, "alien.asm", "asm")
    print("Sprite saved to alien.asm")
